version: '3.7'
services:

  app:
    build: .
    command: sh -c 'pip install --upgrade pip && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/app
    networks:
      - default
    depends_on:
      - db

  db:
    image: 'mariadb:10'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'db-r00t-dev'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'cconverter'
      MYSQL_USER: 'cconverter'
      MYSQL_PASSWORD: 'cconverter-pass'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default

  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.vue-app
    command: sh -c "yarn install;chmod -R a+rwx node_modules;yarn dev"
    volumes:
      - .:/app
    networks:
      - default

  nginx-venda:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - default
    depends_on:
      - app
