version: '3.7'
services:
  app:
    build: .
    command: sh -c 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - default
    depends_on:
      - db
  db:
    image: 'mariadb:10'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'db-r00t-dev'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'cconverter'
      MYSQL_USER: 'cconverter'
      MYSQL_PASSWORD: 'cconverter-pass'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile.vue-app
    ports:
      - "5173:5173"
    command: sh -c "yarn install;chmod -R a+rwx node_modules;yarn dev"
    volumes:
      - .:/app
    networks:
      - default
